name: Integration test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      statuses: write
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            python3 flex bison clang-format clang-tidy clang-tools clang 
            clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev 
            libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb 
            llvm-dev llvm-runtime llvm python3-clang

      - name: Build and test
        id: test
        timeout-minutes: 1
        run: |
          ./test.py

      - name: Perm issue fix
        if: success() || failure()
        run: git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"

      - name: Upload test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test results
          path: output/junit_results.xml
          reporter: java-junit
          fail-on-error: false