# Integration script for GitHub Actions
# 
# Install act as a GitHub CLI extension to run locally
# https://github.com/nektos/act
# Then run "gh act"
#
# Author : William Huynh <wh1022@ic.ac.uk>


name: Integration test
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      statuses: write
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        id: test
        timeout-minutes: 1
        run: |
          scripts/test.sh
        
      - name: Perm issue fix
        if: success() || failure()
        run: git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"

      - name: Upload test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test results
          path: bin/junit_results.xml
          reporter: java-junit
          fail-on-error: false
